# Assignment 0 problem E

Yuanxing Cheng, A20453410, CS577-f22

In [1]:
import numpy as np

## A

In [2]:
a = np.array([1,2,3])[:,None]
b = np.array([4,5,6])[:,None]
c = np.array([-1,1,3])[:,None]

### 1

In [3]:
2*a-b

array([[-2],
       [-1],
       [ 0]])

### 2

In [4]:
a/np.linalg.norm(a)

array([[0.26726124],
       [0.53452248],
       [0.80178373]])

### 3

In [5]:
np.linalg.norm(a)

3.7416573867739413

In [6]:
i = np.array([1,0,0])[:,None]
j = np.array([0,1,0])[:,None]
k = np.array([0,0,1])[:,None]

In [7]:
np.arccos(np.dot(np.transpose(a),i)/np.linalg.norm(a))

array([[1.30024656]])

### 4

In [8]:
np.arccos(np.dot(np.transpose(a),i)/np.linalg.norm(a))

array([[1.30024656]])

In [9]:
np.arccos(np.dot(np.transpose(a),j)/np.linalg.norm(a))

array([[1.00685369]])

In [10]:
np.arccos(np.dot(np.transpose(a),k)/np.linalg.norm(a))

array([[0.64052231]])

### 5

In [11]:
np.arccos(np.dot(np.transpose(a),b)/np.linalg.norm(a)/np.linalg.norm(b))

array([[0.22572613]])

### 6

In [12]:
np.dot(np.transpose(a),b)

array([[32]])

In [13]:
np.dot(np.transpose(b),a)

array([[32]])

### 7

In [14]:
np.linalg.norm(a)*np.linalg.norm(b)*np.cos(np.arccos(np.dot(np.transpose(a),b)/np.linalg.norm(a)/np.linalg.norm(b)))

array([[32.]])

### 8

In [15]:
np.dot(np.transpose(b),a/np.linalg.norm(a))

array([[8.55235974]])

### 9

In [16]:
np.dot(np.array([0,-3,2]),a)

array([0])

### 10

In [17]:
np.cross(np.transpose(a),np.transpose(b))

array([[-3,  6, -3]])

In [18]:
np.cross(np.transpose(b),np.transpose(a))

array([[ 3, -6,  3]])

### 11

In [19]:
np.cross(np.transpose(a),np.transpose(b))

array([[-3,  6, -3]])

In [20]:
np.dot(np.cross(np.transpose(a),np.transpose(b)),a)

array([[0]])

In [21]:
np.dot(np.cross(np.transpose(a),np.transpose(b)),b)

array([[0]])

### 12

In [22]:
b-3*a+c

array([[0],
       [0],
       [0]])

### 13

In [23]:
np.dot(np.transpose(a),b)

array([[32]])

In [24]:
np.dot(a,np.transpose(b))

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

## B

In [25]:
A = np.array([[1,2,3],[4,-2, 3],[0,5,-1]])
B = np.array([[1,2,1],[2,1,-4],[3,-2,1]])
C = np.array([[1,2,3],[4,5,6],[-1,1,3]])
d = np.array([1,2,3])[:,None]

### 1

In [26]:
2*A-B

array([[ 1,  2,  5],
       [ 6, -5, 10],
       [-3, 12, -3]])

### 2

In [27]:
np.matmul(A,B)

array([[ 14,  -2,  -4],
       [  9,   0,  15],
       [  7,   7, -21]])

In [28]:
np.matmul(B,A)

array([[  9,   3,   8],
       [  6, -18,  13],
       [ -5,  15,   2]])

### 3

In [29]:
np.transpose(np.matmul(A,B))

array([[ 14,   9,   7],
       [ -2,   0,   7],
       [ -4,  15, -21]])

In [30]:
np.matmul(np.transpose(B),np.transpose(A))

array([[ 14,   9,   7],
       [ -2,   0,   7],
       [ -4,  15, -21]])

### 4

In [31]:
np.linalg.det(A)

54.999999999999964

In [32]:
np.exp(np.linalg.slogdet(A)[1])

54.999999999999964

### 5

In [33]:
np.linalg.det(C)

7.494005416219837e-16

In [34]:
np.linalg.det(B)

-42.00000000000002

In [35]:
np.matmul(B[0,:],B[1,:])

0

In [36]:
np.matmul(B[0,:],B[2,:])

0

In [37]:
np.matmul(B[1,:],B[2,:])

0

### 6

In [38]:
np.linalg.inv(A)

array([[-0.23636364,  0.30909091,  0.21818182],
       [ 0.07272727, -0.01818182,  0.16363636],
       [ 0.36363636, -0.09090909, -0.18181818]])

In [39]:
np.linalg.inv(B)

array([[ 0.16666667,  0.0952381 ,  0.21428571],
       [ 0.33333333,  0.04761905, -0.14285714],
       [ 0.16666667, -0.19047619,  0.07142857]])

### 7

In [40]:
np.linalg.inv(C)

array([[ 1.20095990e+16, -4.00319967e+15, -4.00319967e+15],
       [-2.40191980e+16,  8.00639934e+15,  8.00639934e+15],
       [ 1.20095990e+16, -4.00319967e+15, -4.00319967e+15]])

### 8

In [41]:
np.matmul(A,d)

array([[14],
       [ 9],
       [ 7]])

### 9

In [42]:
np.matmul(A,d)/np.linalg.norm(d)

array([[3.74165739],
       [2.40535118],
       [1.87082869]])

### 10

In [43]:
np.matmul(A,np.matmul(d,np.transpose(d)))/np.linalg.norm(d)

array([[ 3.74165739,  7.48331477, 11.22497216],
       [ 2.40535118,  4.81070235,  7.21605353],
       [ 1.87082869,  3.74165739,  5.61248608]])

### 11

In [44]:
np.matmul(A,d)

array([[14],
       [ 9],
       [ 7]])

### 12

In [45]:
np.matmul(np.linalg.inv(B),d)

array([[1.00000000e+00],
       [2.77555756e-17],
       [0.00000000e+00]])

In [46]:
np.linalg.solve(B,d)

array([[ 1.00000000e+00],
       [ 2.37904934e-17],
       [-1.18952467e-17]])

### 13

In [47]:
np.linalg.solve(C,d)

array([[-8.00639934e+15],
       [ 1.60127987e+16],
       [-8.00639934e+15]])

## C

In [48]:
D = np.array([[1,2],[3,2]])
E = np.array([[2,-2],[-2,5]])
F = np.array([[1,2],[2,4]])

### 1

In [49]:
np.linalg.eig(D)

(array([-1.,  4.]),
 array([[-0.70710678, -0.5547002 ],
        [ 0.70710678, -0.83205029]]))

### 2

In [50]:
np.dot(np.linalg.eig(D)[1][:,0],np.linalg.eig(D)[1][:,1])

-0.19611613513818388

### 3


In [51]:
np.dot(np.linalg.eig(E)[1][:,0],np.linalg.eig(E)[1][:,1])

0.0

### 4

Since $E$ is symmtric, it's eigenvectors are orthogonal. Proofs are in previous part.

### 5

In [52]:
np.matmul(F,np.array([0,0]))

array([0, 0])

### 6

In [53]:
np.matmul(F,np.array([2,-1]))

array([0, 0])

In [54]:
np.matmul(F,np.array([4,-2]))

array([0, 0])

### 7

In [55]:
np.matmul(D,np.array([0,0]))

array([0, 0])